# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#

[[constraint]]
  name = "github.com/18F/hmacauth"
  version = "~1.0.1"

[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "~0.3.0"

[[constraint]]
  name = "github.com/bitly/go-simplejson"
  version = "~0.5.0"

[[constraint]]
  name = "github.com/mreiferson/go-options"
  revision = "77551d20752b54535462404ad9d877ebdb26e53d"

[[constraint]]
  name = "golang.org/x/oauth2"
  revision = "9f3314589c9a9136388751d9adae6b0ed400978a"

[[constraint]]
  branch = "master"
  name = "google.golang.org/api"

[[constraint]]
  name = "gopkg.in/fsnotify.v1"
  source="gopkg.in/fsnotify/fsnotify.v1"
  version = "~1.2.0"
