apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: [variables('KUBE_BOT_IMAGE_NAME')]
  namespace: hotels
spec:
  replicas: 2
  revisionHistoryLimit: 2  
  template:
    metadata:
      labels:
        app: [variables('KUBE_BOT_IMAGE_NAME')]
    spec:
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      containers:
      - name: [variables('KUBE_BOT_IMAGE_NAME')]
        image: "[variables('KUBE_BOT_CONTAINER_REGISTRY')]/[variables('KUBE_BOT_CONTAINER_REPO')]/packagesoauthservice:[variables('KUBE_BOT_IMAGE_TAG')]"
        imagePullPolicy: IfNotPresent
        args:
          - "-upstream=http://packagescampaignmanager-web.hotels"
          - "-provider=azure"
          - "-cookie-name=adminauth"
          - "-cookie-secure=true"
          - "-cookie-expire=168h0m"
          - "-cookie-refresh=2m"
          - "-cookie-secret=Mx9S631sW6tq0ipz1R2mwFkKAdpDzX0L"
          - "-cookie-domain=devservices.webjet.com.au"
          - "-email-domain=*"
          - "-client-id=3aa578e2-6af3-4975-8183-0ea3a4c68a59"
          - "-client-secret=PvP+GLSTp5vqQRrPmhhRtHo+61pYl5K72T63rASJ5p8="
          - "-http-address=http://0.0.0.0:4180"
          - "-azure-tenant=5de0e68c-0afd-4a67-b089-31f168aa4ca0"
          - "-pass-groups=true"
          - "-approval-prompt="
          - "-skip-provider-button=true"
          - "-redirect-url=https://devservices.webjet.com.au/oauthproxy/callback"
        resources:
          requests:
            memory: "50Mi"
            cpu: "100m"
          limits:
            memory: "5120Mi"
            cpu: "1.5"
        ports:
          - containerPort: 4180
      imagePullSecrets:
      - name: registrykey
---
kind: Service
apiVersion: v1
metadata:
  name: [variables('KUBE_BOT_IMAGE_NAME')]
  namespace: hotels
spec:
  selector:
    app: [variables('KUBE_BOT_IMAGE_NAME')]
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4180
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/rewrite-target: /
  name: [variables('KUBE_BOT_IMAGE_NAME')]
  namespace: hotels
spec:
  tls:
  - hosts:
    - devservices.webjet.com.au
    secretName: webjet-tls-ssl 
  rules:
  - host: devservices.webjet.com.au
    http:
      paths:
      - path: /web/admin/
        backend:
          serviceName: [variables('KUBE_BOT_IMAGE_NAME')]
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
  name: [variables('KUBE_BOT_IMAGE_NAME')]-oauth
  namespace: hotels
spec:
  tls:
  - hosts:
    - devservices.webjet.com.au
    secretName: webjet-tls-ssl 
  rules:
  - host: devservices.webjet.com.au
    http:
      paths:
      - path: /oauthproxy
        backend:
          serviceName: [variables('KUBE_BOT_IMAGE_NAME')]
          servicePort: 80

