Kind: kubebot.values/v1
deployment:
  image: oauthservice
  # livenessProbe: /
  port: 4180
  env:
    - name: ENVIRONMENT
      value: production
    - name: SITE
      value: wjau
  args:
    - "-config=/etc/config/oauth2_proxy.cfg"
    - "-upstream=http://packagescampaignmanager-web.hotels/admin/web/packages/serenityservice/,http://itinerarylist-wjau.serviceportal/admin/web/portal/itinerarylist/,http://flightsdatamanagement-web-wjau.flights/admin/web/flights/serenityservice/,http://price-lookup.ui/admin/web/ui/pricelookup/,http://packagesaiwebportal.hotels/admin/web/packages/ai-controller/,http://bsp-refund-web.serviceportal/admin/web/serviceportal/bsp-refund/,http://bsp-refund-api.serviceportal/admin/api/serviceportal/bsp-refund/"      
    - "-provider=azure"
    - "-cookie-name=adminauth"
    - "-cookie-secure=true"
    - "-cookie-expire=12h0m"
    - "-cookie-refresh=10h30m"
    - "-cookie-domain=services.webjet.com.au"
    - "-email-domain=*"
    - "-http-address=http://0.0.0.0:4180"
    - "-azure-tenant=5de0e68c-0afd-4a67-b089-31f168aa4ca0"
    - "-pass-groups=true"
    - "-approval-prompt="
    - "-skip-provider-button=true"
    - "-redirect-url=https://services.webjet.com.au/oauth2/callback"
    - "-pass-user-headers=true"
    - "-pass-groups=true"

secret:
  path: /etc/config

ingress:
  rules:
  - hostname: services.webjet.com.au
    paths:
    - path: /admin
    - path: /oauth2

