apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: [variables('KUBE_BOT_IMAGE_NAME')]
  namespace: oauth
spec:
  replicas: 2
  revisionHistoryLimit: 2  
  template:
    metadata:
      labels:
        app: [variables('KUBE_BOT_IMAGE_NAME')]
    spec:
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      containers:
      - name: [variables('KUBE_BOT_IMAGE_NAME')]
        image: "[variables('KUBE_BOT_CONTAINER_REGISTRY')]/[variables('KUBE_BOT_CONTAINER_REPO')]/oauthservice:[variables('KUBE_BOT_IMAGE_TAG')]"
        imagePullPolicy: IfNotPresent
        args:
          - "-config=/etc/config/oauth2_proxy.cfg"
          - "-upstream=http://packagescampaignmanager-web-nz.hotels/admin/web/packages/serenityservice/,http://itinerarylist-wjnz.serviceportal/admin/web/portal/itinerarylist/" 
          - "-provider=azure"
          - "-cookie-name=adminauth"
          - "-cookie-secure=true"
          - "-cookie-expire=8h0m"
          - "-cookie-refresh=4h0m"
          - "-cookie-domain=services.webjet.co.nz"
          - "-email-domain=*"
          - "-http-address=http://0.0.0.0:4180"
          - "-azure-tenant=5de0e68c-0afd-4a67-b089-31f168aa4ca0"
          - "-pass-groups=true"
          - "-approval-prompt="
          - "-skip-provider-button=true"
          - "-redirect-url=https://services.webjet.co.nz/oauth2/callback"
          - "-pass-user-headers=true"
          - "-pass-groups=true"
        resources:
          requests:
            memory: "750Mi"
            cpu: "10m"
          limits:
            memory: "1024Mi"
            cpu: "1"
        ports:
          - containerPort: 4180
        volumeMounts:
        - name: oauthvolumemount
          mountPath: /etc/config
      volumes:
      - name: oauthvolumemount
        secret:
          secretName: oauth2config
      imagePullSecrets:
      - name: registrykey
---
kind: Service
apiVersion: v1
metadata:
  name: [variables('KUBE_BOT_IMAGE_NAME')]
  namespace: oauth
spec:
  selector:
    app: [variables('KUBE_BOT_IMAGE_NAME')]
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4180
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
  name: [variables('KUBE_BOT_IMAGE_NAME')]
  namespace: oauth
spec:
  tls:
  - hosts:
    - services.webjet.co.nz
    secretName: webjet-tls-ssl 
  rules:
  - host: services.webjet.co.nz
    http:
      paths:
      - path: /admin
        backend:
          serviceName: [variables('KUBE_BOT_IMAGE_NAME')]
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
  name: [variables('KUBE_BOT_IMAGE_NAME')]-oauth
  namespace: oauth
spec:
  tls:
  - hosts:
    - services.webjet.co.nz
    secretName: webjet-tls-ssl 
  rules:
  - host: services.webjet.co.nz
    http:
      paths:
      - path: /oauth2
        backend:
          serviceName: [variables('KUBE_BOT_IMAGE_NAME')]
          servicePort: 80

