Kind: kubebot.values/v1
deployment:
  image: b2c-oauthproxy
  # livenessProbe: /
  port: 4180
  env:
    - name: ENVIRONMENT
      value: production
    - name: SITE
      value: wjau

  args:
    - --config=/etc/config/oauth2_proxy.cfg
    - --provider=oidc
    - --cookie-name=b2c-oauthproxy
    - --cookie-secure=true
    - --cookie-expire=12h0m
    - --cookie-domain=flights.webjet.com.au
    - --email-domain=*
    - --whitelist-domain=.webjet.com.au,.webjet.co.nz,webjetauprod.b2clogin.com
    - --http-address=http://0.0.0.0:4180
    - --oidc-issuer-url=https://login.webjet.com.au/a5bfcd07-7a3a-427e-b3fd-8ac4a34329a7/v2.0/
    - --skip-oidc-discovery=true
    - --login-url=https://login.webjet.com.au/login.webjet.com.au/B2C_1A_signin_TSA_Prod_AU/oauth2/v2.0/authorize
    - --redeem-url=https://login.webjet.com.au/login.webjet.com.au/B2C_1A_signin_TSA_Prod_AU/oauth2/v2.0/token
    - --oidc-jwks-url=https://login.webjet.com.au/login.webjet.com.au/B2C_1A_signin_TSA_Prod_AU/discovery/v2.0/keys
    - --approval-prompt=
    - --skip-provider-button=true
    - --redirect-url=/oauth2/callback
    - --scope=https://webjetauprod.onmicrosoft.com/oauth-proxy/customer.member openid
    - --pass-user-headers=true
    - --session-cookie-minimal=true
    - --user-id-claim=signInName #  To get around missing "email" claim, may use the oid instead
    - --standard-logging=true #needs to enable in prod and fine tune by minimal-log-level
    - --minimal-log-level=INFO  # in prod INFO or WARNING possible values see https://pkg.go.dev/github.com/juju/loggo#Level
    - --auth-logging=false
    - --request-logging=false

secret:
  path: /etc/config
# we are using nginx without ingress
# ingress:
# rules:
# - hostname: services.webjet.com.au
# paths:
# - path: /ota-b2c-oauth

