name: Dev Deployment 

on:
  push:
    branches: [develop,fromB2C,oauthV7] 

env:
  NAMESPACE: oauth
  IMAGENAME: oauthservice
 
jobs:
  build:
    env:
      DEPLOY_DEV_AU: false
      DEPLOY_DEV_NZ: true
     # DEPLOY_PROD: false
    runs-on: [webjet, linux]

    steps:
      - uses: actions/checkout@v2
      - uses: webjet/action-kubernetes-init@v1
        with:
          env-json-base64: ${{ secrets.JSONDATA64 }}

      - name: Notify Teams
        uses: webjet/action-msteams@v1
        with:
          webhook-uri: ${{ secrets.SERVICEPORTAL_MSTEAMS_WEBHOOK  }}

      - uses: webjet/action-build-image@v1
      - uses: webjet/action-push-image@v1

      - name: Deploy DEV WJAU
        if: (env.DEPLOY_DEV_AU != 'false' )
        uses: webjet/action-kubebot-deploy@v1
        with:
          environment: 'dev'
          service: 'oauthservice-wjau'
          manifest: 'pipeline/dev-wjau.yaml'

      - name: Deploy DEV WJNZ
        if: (env.DEPLOY_DEV_NZ != 'false' )
        uses: webjet/action-kubebot-deploy@v1
        with:
          environment: 'dev'
          service: 'oauthservice-wjnz'
          manifest: 'pipeline/dev-wjnz.yaml'

     