name: Dev and Prod Deployment 

on:
  push:
    branches: [ master ]

env:
  NAMESPACE: oauth
  IMAGENAME: oauthservice


jobs:
  build:
    env:
      DEPLOY_DEV: true
      DEPLOY_PROD_AU: true
      DEPLOY_PROD_NZ: true
      DEPLOY_Teamcity: false
      DEPLOY_Tableau: false
    runs-on: [webjet, linux]
    #timeout-minutes: 20 #from https://stackoverflow.com/questions/59073731/set-default-timeout-on-github-action-pipeline

    steps:
      - uses: actions/checkout@v2
      - uses: webjet/action-kubernetes-init@v1
        with:
          env-json-base64: ${{ secrets.JSONDATA64 }}

      - name: Notify Teams
        uses: webjet/action-msteams@v1
        with:
          webhook-uri: ${{ secrets.SERVICEPORTAL_MSTEAMS_WEBHOOK  }}

      - uses: webjet/action-build-image@v1
      - uses: webjet/action-push-image@v1


      - name: Deploy DEV WJAU
        if: (env.DEPLOY_DEV != 'false' )
        uses: webjet/action-kubebot-deploy@v1
        with:
           environment: 'dev'
           service: 'oauthservice-wjau'
           manifest: 'pipeline/dev-wjau.yaml'

      - name: Deploy DEV WJNZ
        if: (env.DEPLOY_DEV != 'false' )
        uses: webjet/action-kubebot-deploy@v1
        with:
           environment: 'dev'
           service: 'oauthservice-wjnz'
           manifest: 'pipeline/dev-wjnz.yaml'

      - name: Deploy PROD WJAU
        if: ( github.event_name != 'workflow_dispatch' && env.DEPLOY_PROD_AU != 'false'  ) || ( github.event_name == 'workflow_dispatch' && github.event.inputs.deployToProd == 'true' )
        uses: webjet/action-kubebot-deploy@v1
        with:
           environment: 'prod'
           service: 'oauthservice-wjau'
           manifest: 'pipeline/prod-wjau.yaml'

      - name: Deploy PROD WJNZ
        if: ( github.event_name != 'workflow_dispatch' && env.DEPLOY_PROD_NZ != 'false'  ) || ( github.event_name == 'workflow_dispatch' && github.event.inputs.deployToProd == 'true' )
        uses: webjet/action-kubebot-deploy@v1
        with:
           environment: 'prod'
           service: 'oauthservice-wjnz'
           manifest: 'pipeline/prod-wjnz.yaml'

      - name: Deploy Teamcity Oauth
        if: (env.DEPLOY_Teamcity != 'false' )
        uses: webjet/action-kubebot-deploy@v1
        with:
          environment: 'dev'
          service: 'teamcityoauthservice'
          manifest: 'pipeline/teamcity.yaml'
          repository: 'bitnami'
          tag: 7

      - name: Deploy Tableau Oauth
        if: (env.DEPLOY_Tableau != 'false' )      
        uses: webjet/action-kubebot-deploy@v1
        with:
          environment: 'dev'
          service: 'tableauoauthservice'
          manifest: 'pipeline/tableau.yaml'
          repository: 'bitnami'
          tag: 7